trigger:
  branches:
    include:
      - master
      - release/v1.0.0

pr:
  branches:
    include:
      - master
      - release/v1.0.0

pool:
  name: LocalAgentPool

variables:
  buildConfiguration: 'Release'
  imageName: 'adminkusofteng2026/marketplace-platform'
  tag: '$(Build.BuildId)'

steps:

  # 1. SDK
  - task: UseDotNet@2
    displayName: 'Install .NET 10.x SDK'
    inputs:
      packageType: 'sdk'
      version: '10.x'

  # 2. Restore dependencies
  - task: DotNetCoreCLI@2
    displayName: 'Restore dependencies'
    inputs:
      command: 'restore'
      projects: 'Marketplace.slnx'

  # Build all projects (incl. tests)
  - task: DotNetCoreCLI@2
    displayName: 'Build solution'
    inputs:
      command: 'build'
      projects: 'Marketplace.slnx'
      arguments: '--configuration $(buildConfiguration) --no-restore'

  # 4. Unit tests  (no database used)
  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: 'test'
      projects: 'Backend/tests/Backend.UnitTests/Backend.UnitTests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'
      publishTestResults: true

  # 5. Integration tests  (no database connection required)
  - task: DotNetCoreCLI@2
    displayName: 'Run integration tests'
    inputs:
      command: 'test'
      projects: 'Backend/tests/Backend.IntegrationTests/Backend.IntegrationTests.csproj'
      arguments: '--configuration $(buildConfiguration) --no-build'
      publishTestResults: true

  # 6. Docker build + push (ONLY if everything above passed)
  - task: Docker@2
    displayName: 'Build and Push Docker image'
    condition: succeeded()
    inputs:
      containerRegistry: 'dockerhub-connection' # from AZ devops Project Settings>Service connections
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(tag)
        latest
